# Generated by Django 5.1.2 on 2024-10-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_da_empresa', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50)),
                ('Nome_do_motorista', models.CharField(max_length=50)),
                ('Numero_da_cnh', models.CharField(max_length=50)),
                ('placa_do_carro', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
