# Generated by Django 5.1.2 on 2024-10-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
    ]
