# Generated by Django 5.1.2 on 2024-10-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_voucher_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10),
        ),
    ]
