# Generated by Django 5.1.2 on 2024-10-13 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_voucher_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='comprovante',
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='comprovantes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='home.voucher')),
            ],
        ),
    ]
